docs: use systempackages in RTD

diff --git a/.readthedocs.yaml b/.readthedocs.yaml
--- a/.readthedocs.yaml
+++ b/.readthedocs.yaml
@@ -10,18 +10,103 @@ build:
   os: ubuntu-24.04
   tools:
     python: "3.12"
+  apt_packages:
+    - bind9
+    - bind9utils
+    - devscripts
+    - distro-info
+    - dnsutils
+    - freeipmi-tools
+    - iputils-ping
+    - isc-dhcp-common
+    - isc-dhcp-server
+    - libpq-dev
+    - lshw
+    - postgresql
+    - pxelinux
+    - python3-aiodns
+    - python3-aiofiles
+    - python3-aiohttp
+    - python3-alembic
+    - python3-apt
+    - python3-asyncpg
+    - python3-attr
+    - python3-authlib
+    - python3-bson
+    - python3-crochet
+    - python3-cssselect
+    - python3-curtin
+    - python3-dev
+    - python3-distro-info
+    - python3-django-piston3
+    - python3-fastapi
+    - python3-formencode
+    - python3-hivex
+    - python3-httplib2
+    - python3-httpx
+    - python3-hvac
+    - python3-joserfc
+    - python3-jsonschema
+    - python3-lxml
+    - python3-macaroonbakery
+    - python3-markupsafe
+    - python3-mimeparse
+    - python3-python-multipart
+    - python3-netaddr
+    - python3-netifaces
+    - python3-novaclient
+    - python3-oauthlib
+    - python3-openssl
+    - python3-packaging
+    - python3-paramiko
+    - python3-passlib
+    - python3-petname
+    - python3-pexpect
+    - python3-prometheus-client
+    - python3-psycopg2
+    - python3-pydantic
+    - python3-pyinotify
+    - python3-pylxd
+    - python3-pyparsing
+    - python3-pypureomapi
+    - python3-pythonjsonlogger
+    - python3-pyvmomi
+    - python3-requests
+    - python3-requests-unixsocket
+    - python3-seamicroclient
+    - python3-sqlalchemy
+    - python3-starlette
+    - python3-structlog
+    - python3-tempita
+    - python3-temporalio
+    - python3-twisted
+    - python3-txtftp
+    - python3-tz
+    - python3-ulid
+    - python3-uvicorn
+    - python3-uvloop
+    - python3-venv
+    - python3-yaml
+    - python3-zhmcclient
+    - python3-zope.interface
+    - syslinux-common
+    - temporal
+    - ubuntu-keyring
+    - wget
   jobs:
     post_checkout:
-    - git fetch --unshallow || true
-    # Cancel building pull requests when there aren't changed in the docs directory.
-    # If there are no changes (git diff exits with 0) we force the command to return with 183.
-    # This is a special exit code on Read the Docs that will cancel the build immediately.
-    # https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition
-    - |
-      if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- 'docs/' '.readthedocs.yaml';
-      then
-        exit 183;
-      fi
+      - git fetch --unshallow || true
+      # Cancel building pull requests when there aren't changed in the docs directory.
+      # If there are no changes (git diff exits with 0) we force the command to return with 183.
+      # This is a special exit code on Read the Docs that will cancel the build immediately.
+      # https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition
+      - |
+        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- 'docs/' '.readthedocs.yaml';
+        then
+          exit 183;
+        fi
+    create_environment:
+      - python -m virtualenv $READTHEDOCS_VIRTUALENV_PATH --system-site-packages
 
 # Build documentation in the docs/ directory with Sphinx
 sphinx:
@@ -31,10 +116,10 @@ sphinx:
 
 # If using Sphinx, optionally build your docs in additional formats such as PDF
 formats:
-- pdf
-- htmlzip
+  - pdf
+  - htmlzip
 
 # Optionally declare the Python requirements required to build your docs
 python:
   install:
-  - requirements: docs/requirements.txt
+    - requirements: docs/requirements.txt
