[r=blake-rouse][bug=][author=blake-rouse] Remove all the old code that is no longer required after adding DNS HA.

diff --git a/services/regiond2/run b/services/regiond2/run
--- a/services/regiond2/run
+++ b/services/regiond2/run
@@ -1,1 +1,36 @@
-../regiond/run
+#!/bin/bash
+# Copyright 2012-2015 Canonical Ltd.  This software is licensed under the
+# GNU Affero General Public License version 3 (see the file LICENSE).
+
+# Exit immediately if a command exits with a non-zero status.
+set -o errexit
+# Treat unset variables as an error when substituting.
+set -o nounset
+
+# Remember where here is.
+here="$(pwd)"
+
+# Move to the project root.
+cd "$(dirname "$0")/../.."
+
+# Start logging, if requested. Not using multilog here right now
+# because there are race issues when restarting.
+[ -z "${logdir:-}" ] || exec &>> "${logdir}/current"
+
+# Prevent reloading if this is running under supervise(8).
+if [ "/proc/${PPID}/exe" -ef "/usr/bin/supervise" ]
+then
+    set -- "$@" --noreload
+fi
+
+# DNS settings, for driving BIND.
+export MAAS_DNS_CONFIG_DIR="$(readlink -f run/named)"
+export MAAS_DNS_RNDC_PORT=5247
+export MAAS_DNS_DEFAULT_CONTROLS=0
+
+# Regiond worker id. (Not Master)
+export MAAS_REGIOND_WORKER_ID=2
+
+# Exec the MAAS API and Web UI Server.
+script="$(readlink -f bin/twistd.region)"
+exec "${script}" --nodaemon --pidfile="" maas-regiond
