[r=allenap][bug=][author=mpontillo] IP range initial API, forms, and cleanup.
   * Change previous migrations to use newly-decided-on types for
     static ranges.
   * Remove distinction between unmanaged and managed DHCP ranges.
     (now simply use "dynamic" as the type)
   * Remove distinction between admin_reserved and user_reserved ranges.
     (now they are both "reserved", but user reserved ranges define a
     user.)
   * Update previously-landed migrations to use the new type names.
   * Update triggers to use new range types.

  Also, drive-by fixes related to getting the CLI working post-rack-integration:

   * Only use the nodegroups/ endpoint to test for authentication
     if "/api/1.0" is in the URL.
   * Add a "whoami" operation to the "users" endpoint.
   * Add the ability to logout() when testing the API.
     (Simply uses a non-OAuth client, and unsets the logged in user.)
   * Have remote-reinstall sync /usr/share/maas/maas, so that settings.py
     can grab the updated API URL.

diff --git a/utilities/remote-reinstall b/utilities/remote-reinstall
--- a/utilities/remote-reinstall
+++ b/utilities/remote-reinstall
@@ -80,6 +80,11 @@ rsync -${rsync_options} etc/maas/ \
     && echo "Success." || die "Syncrhonization failed."
 $ssh_run "chown -R maas:maas /etc/maas"
 
+echo "Updating /usr/share/maas/maas..."
+rsync -${rsync_options} src/maas/ \
+    root@${hostname}:/usr/share/maas/maas \
+    && echo "Success." || die "Syncrhonization failed."
+
 echo ""
 echo "Restarting services and ensuring migrations are up to date..."
 $ssh_run service maas-regiond stop
