[r=rvb][bug=1364617][author=julian-edwards] Detect IPMI password failures and exit with the right status in the IPMI template.

diff --git a/etc/maas/templates/power/ipmi.template b/etc/maas/templates/power/ipmi.template
--- a/etc/maas/templates/power/ipmi.template
+++ b/etc/maas/templates/power/ipmi.template
@@ -62,8 +62,17 @@ issue_ipmi_command() {
         echo workaround |\
         ${ipmi_chassis_config} ${workarounds} ${driver_option} -h ${power_address} -u ${power_user} -p ${power_pass} --commit --filename ${config}
     fi
+
+    # Use C locale to force English error messages.
     result=$(echo workaround |\
-    ${ipmipower} ${workarounds} ${driver_option} -h ${power_address} -u ${power_user} -p ${power_pass} "$@")
+    LC_ALL=C ${ipmipower} ${workarounds} ${driver_option} -h ${power_address} -u ${power_user} -p ${power_pass} "$@")
+
+    if [ $(echo $result | grep -q "password invalid") ]
+    then
+        echo "Invalid password" >&2
+        exit 1
+    fi
+
     case "$result" in
         *:* )
                 # Result looks like the usual IPMI output:
