[r=julian-edwards][bug=][author=allenap] Make the installation of `make` in ephemeral LXC environments more robust within the acceptance suite.
`make` may fail to install because the package lists are out of date, so update them and try again.

diff --git a/acceptance/with-make b/acceptance/with-make
--- a/acceptance/with-make
+++ b/acceptance/with-make
@@ -8,6 +8,12 @@ set -o errexit
 set -o nounset
 
 # Ensure that GNU make is installed.
-sudo -AE apt-get install --assume-yes make
+if ! sudo -AE apt-get install --assume-yes make
+then
+    # The installation of `make` may have failed because the package
+    # lists are out of date, so update them and try again.
+    sudo -AE apt-get update
+    sudo -AE apt-get install --assume-yes make
+fi
 
 exec "$@"
