[r=rvb][bug=1233069][author=jtv] Make maas-import-pxe-files tolerate images that are not present at all.

diff --git a/scripts/maas-import-pxe-files b/scripts/maas-import-pxe-files
--- a/scripts/maas-import-pxe-files
+++ b/scripts/maas-import-pxe-files
@@ -132,25 +132,32 @@ compose_installer_download_url() {
     echo "$base_url/$postfix"
 }
 
+# Fetch MD5SUMS file.  This returns false (i.e. nonzero) in the case of
+# survivable failure, so that the caller can skip this image and move on.
 fetch_server_md5sums() {
     local base_url=$1
-    local ignore
 
     if ! $DOWNLOAD "$base_url/MD5SUMS"
     then
-        fail "Unable to download $base_url/MD5SUMS"
+        echo "Unable to download $base_url/MD5SUMS" >&2
+        return 1
     fi
 
     if [ "x$IGNORE_GPG" == "x" ]
     then
         if ! $DOWNLOAD "$base_url/MD5SUMS.gpg"
         then
-            fail "Unable to download $base_url/MD5SUMS.gpg"
+            echo "Unable to download $base_url/MD5SUMS.gpg" >&2
+            return 1
         fi
 
-        ignore=$(gpg --keyring=$GPG_KEYRING --verify MD5SUMS.gpg MD5SUMS 2>&1) ||
-            fail "Failed to verify MD5SUMS via $GPG_KEYRING ($base_url/MD5SUMS)"
+        if ! gpg --keyring=$GPG_KEYRING --verify MD5SUMS.gpg MD5SUMS >/dev/null 2>/dev/null
+        then
+            echo "Failed to verify MD5SUMS via $GPG_KEYRING ($base_url/MD5SUMS)" >&2
+            return 1
+        fi
     fi
+    return 0
 }
 
 get_md5sum_for_file() {
