LP: #1868908 - start services when not disabled in the snap to run migrations

diff --git a/snap/hooks/install b/snap/hooks/install
--- a/snap/hooks/install
+++ b/snap/hooks/install
@@ -19,6 +19,22 @@ cp "$SNAP/etc/maas/preseeds/curtin_userdata_centos" "$SNAP_DATA/preseeds/curtin_
 cp "$SNAP/etc/maas/preseeds/curtin_userdata_custom" "$SNAP_DATA/preseeds/curtin_userdata_custom.sample"
 cp "$SNAP/etc/maas/preseeds/curtin_userdata_windows" "$SNAP_DATA/preseeds/curtin_userdata_windows.sample"
 
+maas_snap_mode() {
+    cat "$SNAP_COMMON/snap_mode" 2>/dev/null || echo "none"
+}
+
+if [ "$(maas_snap_mode)" = "all" ]; then
+    # When running in all mode and not disabled, start services to ensure
+    # PostgreSQL is running to perform migrations
+    service="${SNAP_INSTANCE_NAME}.supervisor"
+    if snapctl services "$service"  | grep -q disabled; then
+        echo "Can't refresh snap in 'all' mode while disabled." >&2
+        exit 1
+    else
+        snapctl start "$service"
+    fi
+fi
+
 # Perform migrations. Does nothing in 'rack' or 'none' mode.
 "$SNAP/bin/maas-wrapper" migrate --configure
 # Force reconfigure of supervisord as config template might have changed
